[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
upload_speed = 921600      
monitor_speed = 921600
lib_deps = 
    tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
    kosme/arduinoFFT@^2.0
    https://github.com/pschatzmann/arduino-audio-tools.git
